Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,46 +1,57 @@
 version: 2.1
 
-orbs:
-  slack: circleci/slack@4.9.3
-
-executors:
-  linux-executor:
-    docker:
-      - image: cimg/python:3.9
-    working_directory: ~/workspace
-
 jobs:
-  build:
-    executor: linux-executor
-    steps:
-      - checkout
-      - run:
-          name: Show current system date
-          command: date
-
-  test:
-    executor: linux-executor
-    steps:
-      - run:
-          name: Check Python version
-          command: python -version  # Corrected command here
-
-  notify:
+  job1:
     docker:
-      - image: cimg/python:3.9  # You can use the same executor image, or use the slack orb's image
+      - image: circleci/python:3.8
     steps:
-      - slack/notify:
-          event: fail
-          template: basic_fail_1
-      - slack/notify:
-          event: pass
-          template: success_tagged_deploy_1
+      - run:
+          name: Run job 1
+          command: |
+            echo "Running job 1"
+            exit 1  # Simulate failure
+
+  job2:
+    docker:
+      - image: circleci/python:3.8
+    steps:
+      - run:
+          name: Run job 2
+          command: |
+            echo "Running job 2"
+            exit 0  # Simulate success
+
+  job3:
+    docker:
+      - image: circleci/python:3.8
+    steps:
+      - run:
+          name: Run job 3
+          command: |
+            echo "Running job 3"
+            exit 0  # Simulate success
+
+  final_job:
+    docker:
+      - image: circleci/python:3.8
+    steps:
+      - run:
+          name: Always run this job
+          command: echo "This job runs no matter what!"
 
 workflows:
   version: 2
-  build_and_notify:
+  build:
     jobs:
-      - build
-      - test
-      - notify:
-          context: slack-secrets  # Ensure the Slack context is defined
+      - job1
+      - job2
+      - job3
+      - final_job:
+          requires:
+            - job1
+            - job2
+            - job3
+          filters:
+            branches:
+              only: master
+          finish: true  # Ensure this job runs after all other jobs
